try {
    throw Error('Algo sali√≥ mal');
} catch(error){
    console.log(error);
}